[package]
name = "gift-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.3"

[dependencies.gift]
path = ".."

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
